name: CovidTracker Test

on:
  push:
    pull_request:
      branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  job1:
    name: CovidTracker backend Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run backend Tests
        run: mvn -D test="test.java.Backend.**"

  job2:
    needs: job1
    name: CovidTracker GUI Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.1.0

      - name: Run GUI Tests
        run: mvn -D test="test.java.GUI.**""

      - name: Generate test report
        run: mvn surefire-report:report
