name: CovidTracker Test

on:
  push:
    pull_request:
      branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  job1:
    name: CodiTracker Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.1.0

      - name: Build project with Maven
        run: mvn package --file pom.xml

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit
