name: CovidTracker Test

on:
  push:
    pull_request:
      branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run CovidTracker backend Tests
        run: mvn -D test="src/test/java/Backend/*"

  job2:
    needs: job1
    name: CodiTracker GUI Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.1.0

      - name: Run CovidTracker GUI Tests
        run: mvn -D test="src/test/java/GUI/*""

      - name: Generate test report
        run: mvn surefire-report:report
